# Generated by Django 3.2 on 2021-04-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DoB', models.DateTimeField()),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
